- zookeeper/hparam.py
- zookeeper/hparam_test.py
This removes unnecessary loops and ensures that `__getitem__` properly throws `KeyError`s instead of `AttributeError`s
> Speedup __getitem__ and ensure consistent KeyErrors

- azure-pipelines.yml
This PR adds tests against Python 3.6/3.7 and TF 1.13.1/1.14.0/2.0-beta1.
Note that we don't test every possible combination to keep our builds fast.
> Test against Python 3.6/3.7 and TF 1.13.1/1.14.0/2.0-beta1

- README.md
- zookeeper/cli.py
- zookeeper/cli_test.py
When defining models and data preprocessing in separate files, this hook can be used to lazily import model and data files in order to setup the registry. This can be very useful to speed up shell autocompletion results since TensorFlow takes very long to import and thus would block shell completions if imported normally.
This changes the interface from `@build_train` to `@build_train()` or `@build_train(preload_function)`.
> Breaking change: Add support for preload hook

- zookeeper/data.py
This option will fail with TensorFlow 2.0 so let's remove it to stay compatible.
> Remove experimental slack

- azure-pipelines.yml
This will use [`pytest-azurepipelines`](https://pypi.org/project/pytest-azurepipelines/) which should cleanup our CI config.
> Simplify CI config using pytest-azurepipelines

- setup.py
- zookeeper/cli.py
- zookeeper/data.py
- zookeeper/data_vis.py
- zookeeper/registry.py
This PR moves us to `tensorflow-datasets==1.1.0`. This means we can now make a few improvements related to make the input pipeline more reliable and faster.
The main changes are:
- Remove experimental options (they will be enabled by default if we use the new S3 datasets e.g. `imagenet2012:5.0.0`.
- Reduce final prefetch to 1 batch, which should be enough for the current use cases and drastically reduces memory consumption
- Shuffle and cache before image decoding. This should reduce memory consumption of the shuffle and reduce the disk size needed when caching datasets. See https://github.com/tensorflow/datasets/blob/master/docs/decode.md
- Add support for dataset version using a `--dataset-version` option. See https://github.com/tensorflow/datasets/blob/master/docs/datasets_versioning.md …
> Upgrade to tensorflow-datasets-1.1.0

- README.md
- examples/train.py
- zookeeper/cli_test.py
- zookeeper/data.py
This allows us to directly proccess raw image bytes in the preprocess function. This can be use for compatibility with external preprocessing implementations or for speed in order to use fused decode and crop implementations.
The following functions will now produce the same output:
```python
@registry.register_preprocess("mnist")
def default(image):
return image
@registry.register_preprocess("mnist")
def raw(bytes):
return tf.image.decode_image(bytes)
```
Note: Once we start using zookeeper for application other than image classification, we need to make this more general, but for now let's keep it simple.
> Support preprocess functions that expect bytes

- zookeeper/data.py
This allows us to use datasets that are not available in the upstream version of `tensorflow/datasets`.
> Pass data_dir to builder

- zookeeper/preprocessing.py
- zookeeper/preprocessing_test.py
This bug was introduced in #41
@koenhelwegen Thanks for catching that.
> Correctly pass is_training to preprocess functions

- zookeeper/data.py
- zookeeper/preprocessing.py
- zookeeper/preprocessing_test.py
This is useful in cases where the same preprocessing is to be used for different datasets, but slight differences are necessary depending on which dataset is used. Rather than defining a new pre-processing class for each dataset, you can just re-use the same one and implement the appropriate logic.
> Add support for passing a dataset name to Preprocessing class

- zookeeper/cli.py
This makes the tfds progressbar optional since it doesn't work well when running it on a cluster that can't handle ANSI escape codes.
> Disable tfds progressbar by default

- examples/larq_experiment.py
Calling `model.fit()` without without repeating the dataset is now supported in TF 2, so we can simplify the example.
> Fix example and remove dataset repeat

- zookeeper/component.py
Currently, zookeeper just throws `AttributeError` when a nonexistent attribute is accessed. This gives a bit more info.
> Throw more meaningful AttributeError

- zookeeper/cli.py
- zookeeper/cli_test.py
- zookeeper/utils.py
Previously, it was not possible to pass paths (which included colons ':') through the CLI because `ast.literal_eval` threw a `SyntaxError` instead of a `ValueError`.
> Allow paths to be passed through the CLI, and add CLI tests.

- zookeeper/cli_test.py
- zookeeper/component.py
- zookeeper/component_test.py
- zookeeper/utils.py
Additionally adds a few type annotations and adds a utils function to get the name of a type, for cleaner error messages.
> Close type-checking loophole. Closes #68.

- zookeeper/component.py
- zookeeper/component_test.py
Also, allow `__init__` to be overriden as long as it doesn't define
positional arguments.
> Configure only the top-level reference to a component. Closes #72.

- zookeeper/tf/preprocessing.py
With `tfds==1.3.2` the example would fail with `AttributeError: module 'tensorflow_datasets.core' has no attribute 'base'`
> Fix tfds import

- zookeeper/core/component.py
- zookeeper/core/component_test.py
This PR slightly changes the coloured string representation. It removes the spacing for the keyword arguments and makes the printing multicolour:
> Change component colouring in __repr__

- .github/workflows/unittest.yml
- examples/larq_experiment.py
- zookeeper/tf/experiment.py
Unfortunately there is no way to lazily compute `callbacks` if it is a CLI overwritable attribute, so let's remove everything that in practice won't be overwritten from the CLI
> Remove metrics, learning_rate_schedule and callbacks from experiment class

- README.md
- examples/larq_experiment.py
- setup.py
- zookeeper/__init__.py
- zookeeper/core/__init__.py
- zookeeper/core/cli_test.py
- zookeeper/core/component.py
- zookeeper/core/component_test.py
- zookeeper/core/field.py
- zookeeper/core/field_test.py
- zookeeper/core/partial_component.py
- zookeeper/core/partial_component_test.py
- zookeeper/core/task.py
- zookeeper/core/task_test.py
- zookeeper/core/utils.py
- zookeeper/tf/dataset.py
- zookeeper/tf/experiment.py
- zookeeper/tf/preprocessing.py
Components no longer automatically pick-up all type-annotated descriptors as fields. Instead, the user now has to explicitly define a `Field()` (for non-sub-component fields) or a `ComponentField()` (for sub-component fields). This API change slightly increases verbosity but should reduce user confusion.
Also introduces a `PartialComponent` class.
> Make component fields explicit

- zookeeper/core/component_test.py
- zookeeper/core/field.py
- zookeeper/core/field_test.py
This allows a component to effectively be optional, by letting `None` be passed into a `ComponentField`.
This feature is necessary for Larq Zoo.
> Allow `ComponentField`s to be optional.

- zookeeper/core/component.py
- zookeeper/core/component_test.py
- zookeeper/core/field.py
- zookeeper/core/field_test.py
This PR reverts the previous behaviour of allowing `None` values in `ComponentFields`, and instead allows the ability (in all fields) to specify that a value need not be provided.
> Add `allow_missing` as a flag to `Field`s and `ComponentField`s.

- zookeeper/core/component_test.py
I meant to include this in #115 but accidentally omitted it.
> Add extra test for `allow_missing` fields.

- zookeeper/core/component.py
I was confused by the inheritance behaviour in the component class; I added a few lines to make clear that defaults are not inherited from parents, while explicitly passed values are inherited.
> Extend component example

- zookeeper/tf/experiment.py
Keras / Tensorflow allows for lists of losses when a model has multiple outputs. This change reflects this option in the Experiment loss field's type hint.
> Option for Sequence of losses (for models with multiple outputs)

- zookeeper/tf/experiment.py
When training multi output models, Keras allows to use `loss=None` for some branches. This PR adapts the typings to support this.
> Allow None in Keras loss multitask loss

- zookeeper/core/component.py
- zookeeper/core/component_test.py
This should make the string output cleaner, especially when there
is a deep nested tree of lots of inherited components.
> Shorten the component `str` output by supressing inherited values.

- zookeeper/core/component.py
- zookeeper/core/component_test.py
Fixes the bug mentioned in https://github.com/larq/zookeeper/pull/206#issuecomment-737396937. Also fixes another bug where printing a component that contains a tensor `Field` would throw a TensorFlow error, because the comparison with the parent value returned a boolean tensor rather than a boolean. This led TF to believe we were running in graph mode.
It would be good to add more unit tests for having an empty field with `allow_missing`, and for using tensors in various places, as both of these issues could have been identified through unit tests (we're probably not really testing the printing)
> Fix _list_field_strings

- zookeeper/core/component.py
- zookeeper/core/component_test.py
- zookeeper/core/factory.py
- zookeeper/core/factory_registry.py
- zookeeper/core/field.py
- zookeeper/core/partial_component.py
- zookeeper/core/task.py
- zookeeper/core/task_test.py
- zookeeper/core/utils.py
- zookeeper/tf/dataset.py
- zookeeper/tf/experiment.py
- zookeeper/tf/preprocessing.py
Which is responsible for calling 'configure' on itself. Allows the user to override default values, change the config dict, etc.
> Add __configure__ function to component 

- .github/workflows/lint.yml
- setup.py
- zookeeper/core/component.py
- zookeeper/core/component_test.py
- zookeeper/core/factory.py
- zookeeper/core/factory_registry.py
- zookeeper/core/field.py
- zookeeper/core/partial_component.py
- zookeeper/core/task.py
- zookeeper/core/task_test.py
- zookeeper/core/utils.py
- zookeeper/tf/dataset.py
- zookeeper/tf/experiment.py
- zookeeper/tf/preprocessing.py
Low priority, just to prevent future frustration. Doesn't need to be in 1.1.0.
> Format docstrings with docformatter

- zookeeper/core/component.py
- zookeeper/core/component_test.py
- zookeeper/core/task.py
Previously, components were greedily configured in a depth-first traversal of the component tree, meaning that instances which were inherited could get configured at the 'wrong' (non-topmost) level. This was a source of hard-to-identify bugs - e.g. @timdebruin and I ran into #226. This PR fixes that bug by configuring components in a breadth-first order. This guarantees that if a component instance appears multiple times in the component tree (because of inheritence), then it will be configured precisely once, at the *highest level*.
Unfortunately, I wasn't able to get this breadth-first configuration to naturally work with the existing `__component_configure__` method (cc @jneeven). This is because a breadth-first traversal order requires 'external ordering' and would mean that the …
> Perform component configuration in a breadth-first order.

- .github/workflows/lint.yml
- zookeeper/core/component.py
The colour codes are never used in the code, so we can safely remove the imports
> Remove unused colorama import

- zookeeper/core/component.py
- zookeeper/core/component_test.py
This implements most of [`ItemsView`](https://docs.python.org/3/library/collections.abc.html#collections.abc.ItemsView) for components, which means that components can be iterated through, yielding pairs of `(field_name, field_value)`. Importantly, this view is a flattened representation including the fields of all sub-components.
As a result, `dict(component_instance)` is a meaningful construction. To illustrate, here is an example of `dict(component_instance)` for a component with a nested sub-component:
```python
{
"a": 10, # Normal field
"b": (5, -42.3), # Normal field
"child": "namespace.filename.Child", # Component field - the qualified name of the class that's being used
"child.b": (-1, 0.0), # Normal field (of sub-component)
}
```
In particular, this dict is the precise, minimal …
> Implement the `ItemsView` protocol for component instances. Closes #237.

- setup.py
We seem to semi-frequently get burnt by depenencies being updated that break CI. We can hopefully make things easier by pinning all test dependencies and limiting the main dependencies so that a dependabot update PR is made each time (thus triggering CI and catching upgrades that break things).
> Limit dependencies and pin test dependencies.

- .github/workflows/unittest.yml
CI was failing since yesterday because of a mismatching Keras version as suggested on [SO](https://stackoverflow.com/a/69830680/4807429). By explicitly installing `keras==2.6.0` it is resolved. It was caused by keras 2.7 being released yesterday (https://pypi.org/project/keras/#history) and since we don't pin it this caused issues.
> Fix CI issue by pinning Keras version to 2.6 for TF <= 2.6

- .github/workflows/release-notes.yml
It would fail before (e.g. https://github.com/larq/zookeeper/actions/runs/5520583226/jobs/10067409407) with:
```
Error: Unable to resolve action `release-drafter/release-drafter@v5.22`, unable to find version `v5.22`
```
I've now set the version to what is recommended [here](https://github.com/release-drafter/release-drafter).
> Update to the latest release-drafter

- .github/workflows/publish.yml
This should fix a warning shown e.g. here: https://github.com/larq/zookeeper/actions/runs/5521227582
```
build: # >> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1
You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.
```
> Use latest version of pypa/gh-action-pypi-publish
