- CONTRIBUTING.md
I have added a CONTRIBUTING.md file to this project to address pending Issue #17. Please let me know if you would like additional information to be added to this file but I hope that it can serve as a base to build upon.
> Create CONTRIBUTING.md file (Issue #17)

- README.md
- setup.py
- zookeeper/cli.py
This PR adds a new command to install shell completions for `zookeeper` CLIs.
> Add shell autocompletion

- zookeeper/data.py
This adds the `tf.data.Options` that will be enabled by default in the next release of [TensorFlow datasets](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/tfrecords_reader.py#L55-L63).
I ran a quick test and it seams to slightly improve the input pipeline performance and reduce CPU congestion. But it was hard to quantify, since I was streaming data from GCS.
> Use tf.data.Options to tune input pipeline performance

- README.md
- examples/train.py
- zookeeper/cli.py
- zookeeper/cli_test.py
closes #29 
Beware: this is a breaking change
> remove epochs and fix small bug in example

- azure-pipelines.yml
See https://github.com/larq/larq/pull/159
> Add pyflakes and black linter

- azure-pipelines.yml
See https://github.com/larq/zoo/pull/47
> Fix code coverage path

- zookeeper/data.py
- zookeeper/data_vis.py
- zookeeper/preprocessing.py
This allows us to support shared random transformations for inputs and outputs
> Allow users to overwride Preprocessing.__call__

- zookeeper/cli.py
- zookeeper/cli_test.py
Remove plot command from Zookeeper
> Remove plot command

- examples/larq_experiment.py
Looks like not repeating the dataset, throws annoying warning on TF 2.0 and doesn't work for TF 1.14: https://github.com/tensorflow/tensorflow/issues/32817
This reverts commit 8db5ecc3d8eb9b0f3f64420ed776452012d64371 to be save
> Revert "Remove dataset repeat to simplify example"

- zookeeper/component.py
Thanks to @jneeven for catching this bug.
https://github.com/larq/zookeeper/blob/7422f8c1435d002a12bfced8ca313b62850f9e81/zookeeper/component.py#L181
The check above for `name in self.__component_annotations__` means that if we have the following scenario:
```python
class A(Component):
z: int
class B(Component):
a: A
class C(Component):
b: B
z: int = 5
c = C()
c.configure({})
print(c.b.a.z)
```
the last line will incorrectly throw an `AttributeError`, because the parent `b: B` has no annotation `z`. As `z` is defined on the grandparent `c: C` however, the output should be `5`.
We can safely get rid of the check, which will fix this issue.
> Fix `AttributeError` false-positive.

- .github/workflows/lint.yml
- .gitignore
- setup.cfg
- setup.py
- zookeeper/__init__.py
- zookeeper/cli.py
- zookeeper/component.py
- zookeeper/component_test.py
- zookeeper/dataset.py
- zookeeper/experiment.py
- zookeeper/model.py
- zookeeper/preprocessing.py
- zookeeper/task.py
- zookeeper/task_test.py
- zookeeper/utils.py
Add type checking with `pytype`. 
Use `flake8` rather than `pyflakes`.
Enforce import order with `isort`.
> Improve linting.

- examples/larq_experiment.py
Just a bit of cleanup and some reordering of data pipeline to support map and batch vectorization
> Simplify example

- zookeeper/core/component.py
- zookeeper/core/component_test.py
This PR depends on #110, so is just a draft for now until that gets merged.
> Add a post-configure hook for components. Closes #89.

- zookeeper/core/field.py
This bug would not have been possible in a strongly typed language....
> Fix `ComponentField` error message.

- zookeeper/core/utils.py
Prompted by discussion in larq/zoo#138.
> Fix immutability check: sets are not immutable.

- .github/workflows/unittest.yml
See https://github.com/larq/zoo/pull/146
> Upload coverage report without token

- setup.py
Make a point-release to fix #140.
> :arrow_up: v1.0.1

- .github/workflows/unittest.yml
> Fix CI by pinning TFDS for old TF versions.

- setup.py
- zookeeper/__init__.py
- zookeeper/test_version.py
> Add __version__ property.

- setup.py
#209 fixes https://github.com/larq/zoo/pull/264, would be good to get this release.
> :arrow_up: 1.0.6

- zookeeper/core/component.py
- zookeeper/core/component_test.py
Don't cache field values prior to configuration, except for values generated from field default value factories. Add extra correctness checks. Extend component unit tests to cover complex behaviour with setattr and field value inheritence.
> Fix usage of `setattr` in complex scenarios with nested components.

- zookeeper/core/component.py
- zookeeper/core/component_test.py
I have manually verified that the test script @jneeven included in #225 passes after this PR. I have also modified it into a CI test case that is included here.
~~This PR depends on #227, and will remain a draft until that PR is merged.~~
> Ensure the component parent attribute is set correctly. Closes #225.

- zookeeper/core/component.py
- zookeeper/core/component_test.py
> Fix the behaviour of `__pre_configure__` with nested components.

- setup.py
Changelog here: https://github.com/larq/zookeeper/releases/tag/untagged-10c0b85f021843a18a48
(incomplete due to a [broken release drafter](https://github.com/larq/zookeeper/pull/373), will fix it manually)
> :arrow_up: 1.3.4
